version: "3"

services:
  app:
    build: .
    restart: always
    container_name: react_adel
    volumes:
      - .:/usr/src/produccion
    ports:
      - "3000:3000"
    networks:
      - default
      - adel-react

networks:
    default:
    adel-react:
      external: true